### ISSUE TITLE
LineIterator fails with ERROR: MethodError: Cannot `convert` an object of type 

### ISSUE THREAD

**Issue by gallir** [danielw2904/JSONLines.jl#4]
Hi,
  I'm getting the following error when trying to read a JSONLines' file:

julia> li = LineIndex("sunhotels-xmlapitraces.json")
ERROR: MethodError: Cannot `convert` an object of type 
  Type{Union{Nothing, String}} to an object of type 
  Union{DataType, UnionAll}
Closest candidates are:
  convert(::Type{S}, ::T) where {S, T<:CategoricalArrays.CategoricalValue} at /home/gallir/.julia/packages/CategoricalArrays/0ZAbp/src/value.jl:68
  convert(::Type{T}, ::T) where T at essentials.jl:171
Stacktrace:
 [1] setindex!(::OrderedCollections.OrderedDict{Symbol,Union{DataType, UnionAll}}, ::Type{T} where T, ::Symbol) at /home/gallir/.julia/packages/OrderedCollections/BvIBz/src/ordered_dict.jl:291
 [2] LineIndex(::Array{UInt8,1}, ::Int64, ::Int64, ::Int64, ::Nothing, ::UnitRange{Int64}, ::Int64) at /home/gallir/.julia/packages/JSONLines/a4kId/src/LineIndex.jl:51
 [3] #LineIndex#6 at /home/gallir/.julia/packages/JSONLines/a4kId/src/LineIndex.jl:76 [inlined]
 [4] LineIndex(::String) at /home/gallir/.julia/packages/JSONLines/a4kId/src/LineIndex.jl:76
 [5] top-level scope at REPL[2]:1

Find attached sample of the first json file: [json_sample.txt](https://github.com/danielw2904/JSONLines.jl/files/5401643/json_sample.txt)

LineIterator works, wbut it's very slow for reading jsons into a dataframe.
julia> lit = LineIterator("sunhotels-xmlapitraces.json")
LineIterator(UInt8[0x7b, 0x22, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d  …  0x79, 0x22, 0x3a, 0x6e, 0x75, 0x6c, 0x6c, 0x7d, 0x0d, 0x0a], 1, 108104445, nothing)
julia> lit[1]
┌ Warning: Indexin LineIterators is slow. Consider using LineIndex instead.
└ @ JSONLines ~/.julia/packages/JSONLines/a4kId/src/LineIterator.jl:43
JSON3.Object{SubArray{UInt8,1,Array{UInt8,1},Tuple{UnitRange{Int64}},true},Array{UInt64,1}} with 32 entries:
  :StartTime             => 1602806403
  :StopTime              => 1602806403
  :ResponseTimeMillis    => 24
  :HotelsToSearch        => 1
  :HotelsReturned        => 1
  :ReturnedHotels        => [14997]
  :RoomsReturned         => 8
  :BrandID               => 15
  :AgentID               => 28554
  :AgentImpersonatingID  => -1
  :NumberOfRooms         => 1
  :NumberOfAdults        => 2
  :NumberOfChildren      => 0
  :NumberOfInfants       => 0
  :B2C                   => true
  :HasLiveSearches       => false
  :AgentIsTestUser       => false
  :CustomerCountry       => "1"
  :UserHostName          => "expedia-search.sunhotels.net"
  :UserIP                => "34.216.110.57, 10.190.190.193"
  :Language              => "en"
  :CheckInDate           => "2020-11-08T00:00:00.000"
  :CheckOutDate          => "2020-11-13T00:00:00.000"
  :SearchedDestinations  => [15]
  :SearchedHotels        => [14997]
  :SearchedResorts       => Union{}[]
  :SearchedDestinationId => nothing
  :Server                => "WIN-AESG5RM48VS"
  :DataCenter            => "aws-eu-west-1"
  :ErrorDetails          => nothing
  :HasErrors             => false
  :SearchKey             => nothing

**Comment by danielw2904** [comment]
Hi,

I will investigate and fix asap. In the meantime could you try a different value for the `schemafrom` parameter. E.g. `1:1000`?

**Comment by danielw2904** [comment]
Maybe I did something wrong but I had to preprocess the sample file with the following commands to get a valid JSONLines file

```
tr -d '\n' < testf.jsonl  >> testf2.jsonl
 sed 's/}/}\n/g' testf2.jsonl >> testf2.jsonl
```

Basically first removing all newlines and then adding newlines after the `}`. But this was not the issue just making sure.

The problem was that I typed the dictionary that stores the column types too restrictively. The test file now works for me with the update in [the most recent commit](https://github.com/danielw2904/JSONLines.jl/commit/6c59abcd2cb5e56619ab43cedfb3fd18d241e492)

**Comment by danielw2904** [comment]
Please update to the newest version and see if the error persists. I managed to get the tests passing on nightly and merged the update.

**Comment by gallir** [comment]
Thanks @danielw2904, still the same error

pkg>   [24c2b838] JSONLines v2.0.1 `https://github.com/danielw2904/JSONLines.jl#master`

julia> li = LineIndex("sunhotels-xmlapitraces.json")
ERROR: MethodError: Cannot `convert` an object of type 
  Type{Union{Nothing, String}} to an object of type 
  Union{DataType, UnionAll}
Closest candidates are:
  convert(::Type{S}, ::T) where {S, T<:CategoricalArrays.CategoricalValue} at /home/gallir/.julia/packages/CategoricalArrays/0ZAbp/src/value.jl:68
  convert(::Type{T}, ::T) where T at essentials.jl:171
Stacktrace:
 [1] setindex!(::OrderedCollections.OrderedDict{Symbol,Union{DataType, UnionAll}}, ::Type{T} where T, ::Symbol) at /home/gallir/.julia/packages/OrderedCollections/BvIBz/src/ordered_dict.jl:291
 [2] LineIndex(::Array{UInt8,1}, ::Int64, ::Int64, ::Int64, ::Nothing, ::UnitRange{Int64}, ::Int64) at /home/gallir/.julia/packages/JSONLines/a4kId/src/LineIndex.jl:51
 [3] #LineIndex#6 at /home/gallir/.julia/packages/JSONLines/a4kId/src/LineIndex.jl:76 [inlined]
 [4] LineIndex(::String) at /home/gallir/.julia/packages/JSONLines/a4kId/src/LineIndex.jl:76
 [5] top-level scope at REPL[6]:1

Find attached the complete zipped json I'm using for testing.
[sunhotels-xmlapitraces.zip](https://github.com/danielw2904/JSONLines.jl/files/5407622/sunhotels-xmlapitraces.zip)

**Comment by danielw2904** [comment]
Strange. I cannot replicate this. 

This is the script I use:

```
using Pkg
Pkg.activate(".") # new env
Pkg.add("JSONLines")

using JSONLines
l = LineIndex("sunhotels-xmlapitraces.json")
```

**Comment by gallir** [comment]
I repeated your lines (i.e. activating a new env) and t worked! Thanks.

Now tested exporting to a DataFrame, it takes a long time, but don't know if it's a JSON3 or DataFrame issue.
julia> @time df = LineIndex("sunhotels-xmlapitraces.json") |> DataFrame;
 33.395239 seconds (74.17 M allocations: 4.110 GiB, 4.18% gc time)

**Comment by danielw2904** [comment]
The main problem is that the line index is a row-wise storage just based on the row-wise nature of jsonlines files. When converting to a DataFrame all the rows have to be parsed and then changed to column-wise storage. A little bit less than half of the time is spent on actually reading the file and parsing it (LineIndex just creates an index of all the lines) when I set `nworkers = 8` on my machine. 

Try the following with the number of cores your machine has:

```
l = LineIndex("sunhotels-xmlapitraces.json", nworkers = 8)
l |> materialize |> DataFrame
```

Materialize will do the row parsing in parallel. It will still take some time to change to a column-wise layout though.

**Comment by danielw2904** [comment]
The original error seems to be resolved
