### ISSUE TITLE
LineIndex vs LineIterator

### ISSUE THREAD

**Issue by jtrakk** [danielw2904/JSONLines.jl#5]
What is the difference between `LineIndex` and `LineIterator`? When should each be used?

**Comment by danielw2904** [comment]
LineIndex creates an index of the rows of the file which then allows for a lot of nice operations e.g. parallel parsing of the rows when they are loaded in, indexing into the file. However there is the initial cost of indexing and one Int64 is stored for each line. In general you want to use that in the fashion

`LineIndex("data.jsonl") |> materialize |> DataFrame`

Another tip if you dont want to index the entire file is to use the kw args `skip` and `nrows` to skip lines and then index only the number requested. 

If you just want to iterate over your file and perform some rowwise operation without the initial cost of indexing (eg in case the file is large [>500gb]) you can use the iterator. You can still do eg. Indexing and converting to dataframes with an iterator but its extremely slow as the iterator has to start from the beginning every time and then counts up to the row number. 


Does that clear things up?

**Comment by jtrakk** [comment]
> Does that clear things up?

Yes, thanks.
