### ISSUE TITLE
Read jsonlines from stream

### ISSUE THREAD

**Issue by drathier** [danielw2904/JSONLines.jl#8]
I have a compressed archive of jsonl files and I'd like to load one of those files straight from the compressed archive into jsonlines for reading, but jsonlines seemingly only expects to read from a file on disk. Can it read from an iterator/stream?

**Comment by danielw2904** [comment]
Not at the moment. I will look into it.

**Comment by danielw2904** [comment]
Sorry didn't get to this for a while. What kind of archive are you using? Tar?

**Comment by danielw2904** [comment]
I think reading a file from an archive is beyond the scope of this package but it might be easy to implement e.g. for tar

```
using TranscodingStreams, CodecZlib, JSONLines, Tar

files = ["test0.jsonl", "test1.jsonl", "test2.jsonl"]
for (i,f) in enumerate(files)
    writelines(f, [(filenum = i-1,) for _ in 1:1_000_000])
end
run(`tar -czf test.tar.gz $files`)

function read_tar_gz(archive, file)
    tar = open(archive, read = true) |> GzipDecompressorStream
    path = Tar.extract(f->f.path==file, tar)
    return LineIndex(joinpath(path, file))
end

read_tar_gz("test.tar.gz", "test1.jsonl")
```

Does this help?

**Comment by drathier** [comment]
Yep, tar, and thanks :)
